backend:
  name: github
  repo: leovoon/leovoon.github.io #replace with your githu repo
  branch: master
  squash_merges: true
  open_authoring: true

publish_mode: editorial_workflow
media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media
site_url: "https://leovoon.github.io" # your site name

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    preview_path: blog/{{slug}}
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime" }
      - { label: "Featured Image", name: "heroImage", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", default: []}
      - { label: "Body", name: "body", widget: "markdown" }
